# -*- coding: utf-8 -*-
"""preprocessing_geoai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikWAuiSMhob2ZiG5nsTs7sRuNGwWUAAI

## Generate Images and Mask Tiles
"""

!pip install geotile
!pip install fiona
from geotile import GeoTile
from google.colab import drive
drive.mount('/content/drive/')

PATH_TRAIN_x = r'/content/drive/MyDrive/Course Geoai/Before/Training/train.tif'
PATH_TRAIN_Y = r'/content/drive/MyDrive/Course Geoai/Before/Training/train.shp'
PATH_TEST_x = r'/content/drive/MyDrive/Course Geoai/Before/Testing/test.tif'
PATH_TEST_Y = r'/content/drive/MyDrive/Course Geoai/Before/Testing/test.shp'

gt_train = GeoTile(PATH_TRAIN_x)
gt_train.meta

"""## Pemotongan Citra (Tiling)"""

gt_train.generate_tiles(r'/content/drive/MyDrive/Course Geoai/After/train_x_tiles', prefix='train_')
gt_train.rasterization(PATH_TRAIN_Y, '/content/drive/MyDrive/Course Geoai/After/y_train.tif')
gt_train_y = GeoTile('/content/drive/MyDrive/Course Geoai/After/y_train.tif')
gt_train_y.generate_tiles(r'/content/drive/MyDrive/Course Geoai/After/train_y_tiles', prefix='train_')

gt_test = GeoTile(PATH_TEST_x)
gt_test.generate_tiles(r'/content/drive/MyDrive/Course Geoai/After/test_x_tiles', prefix='test_')
gt_test.rasterization(PATH_TEST_Y, '/content/drive/MyDrive/Course Geoai/After/y_test.tif')
gt_test_y = GeoTile('/content/drive/MyDrive/Course Geoai/After/y_test.tif')
gt_test_y.generate_tiles(r'/content/drive/MyDrive/Course Geoai/After/test_y_tiles', prefix='test_')

"""## Generate Tiles dan Menyimpan dalam numpy"""

gt_train.generate_tiles(save_tiles=False)
gt_train_y.generate_tiles(save_tiles=False)
gt_train.convert_nan_to_zero()

gt_train.normalize_tiles()

import numpy as np
gt_train.tile_data.min(), gt_train.tile_data.max()

gt_train.save_numpy('/content/drive/MyDrive/Course Geoai/After//x_train.npy')
gt_train_y.save_numpy('/content/drive/MyDrive/Course Geoai/After//y_train.npy')

gt_test.generate_tiles(save_tiles=False)
gt_test_y.generate_tiles(save_tiles=False)
gt_test.convert_nan_to_zero()
gt_test.normalize_tiles()
gt_test.save_numpy('/content/drive/MyDrive/Course Geoai/After/x_test.npy')
gt_test_y.save_numpy('/content/drive/MyDrive/Course Geoai/After/y_test.npy')

x_train = np.load('/content/drive/MyDrive/Course Geoai/After/x_train.npy')
x_train.max(), x_train.min(), x_train.dtype, x_train.shape

y_train = np.load('/content/drive/MyDrive/Course Geoai/After/y_train.npy')
y_train.max(), y_train.min(), y_train.dtype, y_train.shape

import matplotlib.pyplot as plt
fig, (ax1, ax2) = plt.subplots(1,2)
img = np.random.randint(0, 256)
print (img)
ax1.imshow(x_train[img, :, :, :3])
ax2.imshow(y_train[img, :, :, 0])
ax1.set_title('Image')
ax2.set_title('Mask')
plt.show()