# -*- coding: utf-8 -*-
"""Unet_Geoai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMoN2fV4rIenHgzWboZ7Li8cMcrMg5VF
"""

!pip install -U "numpy<2.0" tensorflow==2.16.2 ml-dtypes==0.3.2 albumentations geotile fiona

!pip uninstall -y jax jaxlib

# Commented out IPython magic to ensure Python compatibility.
import glob
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

from PIL import Image

from tensorflow.keras import Model
from tensorflow.keras.layers import (
    Input,
    Conv2D,
    MaxPooling2D,
    Conv2DTranspose,
    Concatenate,
    Dropout
)

from google.colab import drive
drive.mount("/content/gdrive")

import os
os.chdir(r'/content/gdrive/MyDrive/Course Geoai/After')

train_xx_initial = np.load('x_train.npy')
train_yy_initial = np.load('y_train.npy')
test_xx = np.load('x_test.npy')
test_yy = np.load("y_test.npy")
print(train_xx_initial.shape, train_yy_initial.shape, test_xx.shape, test_yy.shape)

"""## Augmentasi Data"""

import albumentations as A
import numpy as np

transform = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=45, p=0.5),
    A.Affine(scale=(0.5, 1.5), p=0.5),
    A.Affine(translate_percent=(-0.2, 0.2), p=0.5),
])

augmented_images = []
augmented_masks = []

num_augmentations = 3

for i in range(train_xx_initial.shape[0]):
    image = train_xx_initial[i]
    mask  = train_yy_initial[i].astype(np.int32)

    for _ in range(num_augmentations):
        augmented = transform(image=image, mask=mask)

        augmented_images.append(augmented["image"])
        augmented_masks.append(augmented["mask"])

augmented_images = np.array(augmented_images)
augmented_masks  = np.array(augmented_masks)

# append augmented images/masks with original images/masks
train_xx = np.concatenate((train_xx_initial, augmented_images), axis=0)
train_yy = np.concatenate((train_yy_initial, augmented_masks), axis=0)

# release memory
del augmented_images
del augmented_masks

train_xx.max(), train_xx.min(), train_xx.dtype

train_xx.shape, train_yy.shape

num_samples = train_xx.shape[0]
shuffled_indices = np.random.permutation(num_samples)

train_xx = train_xx[shuffled_indices]
train_yy = train_yy[shuffled_indices]

img = np.random.randint(0, 1024)
print(img)
plt.imshow(train_xx[img, :, :, :3])
plt.show()
plt.imshow(train_yy[img, :, :, 0])
plt.show()

"""## Arsitektur Unet"""

x_in = Input(shape=(256, 256, 3))

'''Encoder'''
x_temp = Conv2D(32, (3, 3), activation='relu', padding='same')(x_in)
x_temp = Dropout(0.25)(x_temp)
x_skip1 = Conv2D(32, (3, 3), activation='relu', padding='same')(x_temp)
x_temp = MaxPooling2D((2,2))(x_skip1)
x_temp = Conv2D(32, (3, 3), activation='relu', padding='same')(x_temp)
x_temp = Dropout(0.25)(x_temp)
x_skip2 = Conv2D(32, (3, 3), activation='relu', padding='same')(x_temp)
x_temp = MaxPooling2D((2,2))(x_skip2)
x_temp = Conv2D(64, (3, 3), activation='relu', padding='same')(x_temp)
x_temp = Dropout(0.25)(x_temp)
x_skip3 = Conv2D(64, (3, 3), activation='relu', padding='same')(x_temp)
x_temp = MaxPooling2D((2,2))(x_skip3)
x_temp = Conv2D(64, (3, 3), activation='relu', padding='same')(x_temp)
x_temp = Dropout(0.5)(x_temp)
x_temp = Conv2D(64, (3, 3), activation='relu', padding='same')(x_temp)

'''Decoder'''
x_temp = Conv2DTranspose(64, (3, 3), activation='relu',  padding='same')(x_temp)
x_temp = Dropout(0.5)(x_temp)
x_temp = Conv2DTranspose(64, (3, 3), strides=(2, 2), activation='relu',  padding='same')(x_temp)
x_temp = Concatenate()([x_temp, x_skip3])
x_temp = Conv2DTranspose(64, (3, 3), activation='relu',  padding='same')(x_temp)
x_temp = Dropout(0.5)(x_temp)
x_temp = Conv2DTranspose(64, (3, 3), strides=(2, 2), activation='relu',  padding='same')(x_temp)
x_temp = Concatenate()([x_temp, x_skip2])
x_temp = Conv2DTranspose(32, (3, 3), activation='relu',  padding='same')(x_temp)
x_temp = Dropout(0.5)(x_temp)
x_temp = Conv2DTranspose(32, (3, 3), strides=(2, 2), activation='relu',  padding='same')(x_temp)
x_temp = Concatenate()([x_temp, x_skip1])
x_temp = Conv2DTranspose(32, (3, 3), activation='relu',  padding='same')(x_temp)
x_temp = Dropout(0.5)(x_temp)
x_temp = Conv2DTranspose(32, (3, 3), activation='relu',  padding='same')(x_temp)

'''Use 1 by 1 Convolution to get desired output bands'''
x_temp = Conv2D(32, (1, 1), activation='relu', padding='same')(x_temp)
x_temp = Conv2D(32, (1, 1), activation='relu', padding='same')(x_temp)
x_out = Conv2D(1, (1, 1), activation='sigmoid', padding='same')(x_temp)
# use sigmoid activation here because output values are either 0 or 1

model = Model(inputs=x_in, outputs=x_out)

model.compile(loss='binary_crossentropy', optimizer='adam')

model.summary()

# training model
import tensorflow as tf

# callback function to stop overfitting the model
checkpointer = tf.keras.callbacks.ModelCheckpoint("best_weight.h5", monitor="val_loss", verbose=1, save_best_only=True, mode="min")
earlyStopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=2, verbose=1, mode='min',restore_best_weights=True)

callbacks = [
    earlyStopping,
    checkpointer
    ]
history = model.fit(train_xx, train_yy,
                    validation_data=(test_xx, test_yy),
                    epochs=10,
                    batch_size=8,
                    verbose=1,
                    callbacks=callbacks)

# plot model loss over training and validation data
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

"""## Prediksi"""

from tensorflow.keras.models import load_model
model = load_model("/content/gdrive/MyDrive/Course Geoai/After/best_weight.h5")

threshold = 0.3

pred_test = model.predict(test_xx)
pred_test = (pred_test > threshold).astype(np.uint8)
print(pred_test.shape)

img = np.random.randint(0, 256)
plt.imshow(pred_test[img, :, :, 0])
plt.show()
plt.imshow(test_yy[img,:,:,0])
plt.show()

"""## Accuracy Assessment"""

test_yy = test_yy.astype('uint8')
pred_test = pred_test.astype('uint8')

def calculate_metrics(ground_truth, predicted_mask):
    # Flatten the binary masks to 1D arrays
    ground_truth = ground_truth.ravel()
    predicted_mask = predicted_mask.ravel()

    # True Positives, False Positives, False Negatives
    TP = np.sum((ground_truth == 1) & (predicted_mask == 1))
    FP = np.sum((ground_truth == 0) & (predicted_mask == 1))
    FN = np.sum((ground_truth == 1) & (predicted_mask == 0))

    # True Negatives (optional, may not be needed for all cases)
    TN = np.sum((ground_truth == 0) & (predicted_mask == 0))

    # Calculate Precision, Recall, and F1 Score
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1_score = 2 * (precision * recall) / (precision + recall)

    # Calculate Intersection over Union (IoU)
    iou = TP / (TP + FP + FN)

    return precision, recall, f1_score, iou

print(calculate_metrics(test_yy, pred_test))

"""## Merge Prediciction"""

from geotile import GeoTile

gt = GeoTile("/content/gdrive/MyDrive/Course Geoai/Before/Testing/test.tif")
gt.meta

gt.generate_tiles(save_tiles=False, stride_x=256, stride_y=256)
gt.convert_nan_to_zero()
gt.normalize_tiles()

gt.tile_data.shape, gt.tile_data.max(), gt.tile_data.min(), gt.tile_data.dtype

threshold = 0.3

pred_test = model.predict(gt.tile_data)
pred_test = (pred_test > threshold).astype(np.uint8)
print(pred_test.shape)

gt.tile_data = pred_test

gt.save_tiles("prediction_tiles/")

from geotile import mosaic

mosaic('prediction_tiles/', 'prediction_merge.tif')

import rasterio
import matplotlib.pyplot as plt

with rasterio.open('prediction_merge.tif') as src:
    img = src.read(1)

plt.figure(figsize=(8,8))
plt.imshow(img)
plt.colorbar()
plt.title('Prediction Mosaic')
plt.axis('off')